api/app.js, client/package-lock.json, package-lock.json
fixed a port error where the express server was listening to port 8000 instead of 8080.
=> fixed port 8080 error

client/package-lock.json, client/package.json, client/public/index.html, client/src/components/Register/Register.css, client/src/components/Register/Register.js
=> added react materializecss to support react

server/app.js, server/config/config.json, server/controllers/users.js, server/middleware/users.js, server/models/index.js, server/routes/api/index.js, server/services/user.js
Objective - I deleted and modified files and folders to make sure the backend logic will be more organized. This will make our code more readable when we have more stuff. I wanted to separate HTTP logic layer with Business Logic layer.
REFERENCES : https://www.coreycleary.me/project-structure-for-an-express-rest-api-when-there-is-no-standard-way/
https://github.com/navteniev/QuikBorrow/tree/master/server
=> Restructured the backend

client/package-lock.json, package-lock.json, server/models/Transaction.js, server/models/User.js, server/seeders/user.js
Identical to previous branch but now fitted to updated Master. App runs normally
=> Chris first models

client/package-lock.json, client/src/App.js, client/src/components/Home/Home.js, client/src/components/Test/Step1.js, client/src/components/Test/Step2Detailed.js, client/src/components/Test/Step2EZ.js, client/src/components/Test/Step3EZ.js, client/src/components/Test/Test.css, client/src/components/Test/Test.js, client/src/components/UserInput/UserInput.js
Still going to be working on this branch. Just pushing what I have now so it'll show up on heroku for evaluation.
I've created and linked a Test.js file, which contains the integration of the algorithm I've made.
=> User input test kc

client/package-lock.json, client/src/components/Camera/Camera.js, client/src/components/Camera/ImagePreview.js, package-lock.json
=> Camerasave

client/src/components/Register/Register.js, client/src/utils/api.js, package-lock.json, package.json, server/app.js, server/controllers/users.js, server/middleware/validatorErrors.js, server/models/Transaction.js, server/models/User.js, server/routes/api/index.js, server/routes/api/signin.js, server/routes/api/signup.js, server/routes/api/users.js, server/routes/index.js, server/services/user.js
App can now save users to DB using Register page. Backend register route connected with Register component by using axios package. Password is hashed on submit. Need to add redirect and error handlers in future.
=> Chris register

client/package-lock.json, server/app.js, server/migrations/20200321203729-add-balance-to-user.js, server/models/User.js
Added the 'balance' column to the User model. Also created a migration for it. App still working and all created users begin with a default balance of 0.00
=> added balance column to User model along with migration

client/package-lock.json, client/package.json, package-lock.json
Made a package update to keep up to date with current  npm. This is important due to the many warnings we been experiencing whenever we run the application from localhost.
=> Package Updates, be sure to do npm install

client/package-lock.json, server/controllers/transactions.js, server/routes/api/index.js, server/routes/api/transactions.js, server/services/transaction.js
=> Jimmy routes

server/controllers/users.js, server/routes/api/users.js, server/services/user.js
able to now search user by name
=> Search user

client/package-lock.json, client/package.json, client/src/components/Login/Login.js, client/src/components/Register/Register.js, client/src/utils/api.js, server/app.js, server/controllers/users.js, server/migrations/20200321203729-add-balance-to-user.js, server/migrations/20200401004314-User_friends _and_username.js, server/migrations/20200401010945-Transactions participants.js, server/models/Transaction.js, server/models/User.js, server/routes/api/users.js, server/services/user.js
Updated User and Transaction model as per our meeting today. Users now only have a UNIQUE username and a UNIQUE email. They also have an array of ints for their 'Friends'. Transactions now have an array of integers for 'Participants'.
I've updated 'Name --> Username' in our app (front-end & back-end) and made sure all routes are still working. 
Make sure to set your db sync to true and run app to update the DB.
=> Chris models update

client/package-lock.json, server/app.js, server/controllers/users.js, server/routes/api/users.js, server/services/user.js
created function to add friends
=> Jimmyadd friends

client/src/App.js, client/src/components/Login/Login.js, client/src/components/Register/Register.js, client/src/index.js
The backend login is now connected to the frontend. When the user provides the correct username and password, they will be redirected to the home page otherwise  they still stay on the login page. 
The next step is to update the navbar, meaning, when the user is logged in, I want to display the username and logout option instead of login and register.
=> frontend login works

client/src/App.js, client/src/components/Login/Login.js, client/src/components/Register/Register.js, client/src/components/Sidebar/LoginRegisterRedirect.js, client/src/components/Sidebar/ProfileLogOutRedirect.js, client/src/components/Sidebar/Sidebar.js, client/src/utils/api.js
See https://github.com/ChibiKev/Split-It/issues/74
=> navbar updates if the user is logged in or not

client/src/App.js, client/src/components/Sidebar/LoginRegisterRedirect.js, client/src/components/Sidebar/ProfileLogOutRedirect.js, client/src/components/Sidebar/Sidebar.js
https://stackoverflow.com/questions/49162311/react-difference-between-route-exact-path-and-route-path
In app.js of our react app I changed the <Route path="/" component={Home} /> to <Route exact path="/" component={Home} />
=> minor fix for routes in App.js

client/src/App.js, client/src/components/Profile/Profile.js, client/src/components/Sidebar/ProfileLogOutRedirect.js, client/src/components/Sidebar/Sidebar.js, client/src/utils/api.js, server/services/user.js
Working with Alex and Christian we made improvements to the user profile page. 
If a user is not logged in, a text will be displayed indicating they do not have permission to access the profile info.
Profile pages are also dynamic now so they will be /profile/1 or /profile/2 instead of /profile
See https://github.com/ChibiKev/Split-It/issues/56
=> Route authorization for profile and dynamic profile pages

client/src/App.js, client/src/components/Payments/Payments.css, client/src/components/Payments/Payments.js, client/src/components/Sidebar/ProfileLogOutRedirect.js, server/app.js
=> new Payment component added

client/src/App.js, client/src/components/Payments/Payments.css, client/src/components/Payments/Payments.js
=> Alex payments

server/controllers/transactions.js, server/models/Transaction.js, server/services/transaction.js
=> updated Transaction table and POST route

client/src/App.js, client/src/components/Payments/Payments.js, client/src/utils/api.js, server/controllers/users.js, server/routes/api/users.js
api call to backend for adding balance to user account.
=> Jimmy add balance

client/src/components/Friends/Friends.js, client/src/utils/api.js, server/controllers/friendships.js, server/routes/api/friendships.js, server/services/friendship.js
Not done with friend requests, will have to continue this in another branch.
=> Chris friend requests

client/src/components/Friends/Friends.js, client/src/components/History/History.js, client/src/utils/api.js, server/controllers/transactions.js, server/routes/api/transactions.js, server/routes/api/users.js, server/services/transaction.js
History page now working for logged in users.
=> Chris history

client/src/components/Payments/Payments.js, client/src/utils/api.js, server/controllers/users.js, server/services/user.js
Payment page now allows users to pay for the transactions they were a part of. Add to Funds also working thanks to Kevin.
=> Chris payment back

client/src/components/Friends/Friends.js, client/src/utils/api.js, server/controllers/friendships.js, server/routes/api/friendships.js, server/services/friendship.js
Friends Page working front and back. Only issue that remains is a logged in User being able to send a friend request to someone who has sent them a request. 
Feel free to play around with it and let me know if there are any cases you find that break it. I'll do a hotfix at some point for these issues.
=> Chris friends2

client/src/components/Friends/Friends.js
I will mark the 400th commit c:
=> Added Usernames to friends

client/src/components/Friends/Friends.js, client/src/utils/api.js, server/services/friendship.js
Can no longer add a friend if you have sent them a request already or they have sent you one. An alert pops up telling user to check their requests when attempting to do so.
=> Chris add friend bug

client/src/components/Profile/Profile.js, client/src/utils/api.js, server/controllers/users.js, server/routes/api/users.js, server/services/user.js
Email can now be edited in User Profile page. Checks to see if email is already taken.
=> Chris edit profile
